[package]
name = "impp"
version = "0.4.0"
authors = ["mad-de <cev_madde@msn.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
regex = "1.2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
openssl = { version = "0.10", features = ["vendored"] }
ureq = "0.11"

